### PR TITLE
feat(cli): introduce simple CLI

### PR DESCRIPTION
**Pull request by jia200x**
This PR adds a very simple CLI to output CSV data.

Usage:
```
 python open-sir.py --help
usage: open-sir.py [-h] [-m {sir,sirx}] -p PARAMETERS -i INITIAL_CONDS
                   [-t TIME]

optional arguments:
  -h, --help            show this help message and exit
  -m {sir,sirx}, --model {sir,sirx}
  -p PARAMETERS, --parameters PARAMETERS
  -i INITIAL_CONDS, --initial-conds INITIAL_CONDS
  -t TIME, --time TIME
```

Example usage:
```
 python open-sir.py -p '[1.099537037037037e-05, 4.398148148148148e-06]' -i '[341759,241,0]' -t 1728000 
```

<details><summary>OUTPUT</summary>

```
Seconds,S,I,R
0.000000000000000000e+00,3.417590000000000000e+05,2.410000000000000000e+02,0.000000000000000000e+00
6.939759036144578204e+03,3.417401948525112239e+05,2.522775735839168760e+02,7.527573904817439931e+00
1.387951807228915641e+04,3.417205127081655664e+05,2.640806470882076837e+02,1.540664474618128033e+01
2.081927710843373643e+04,3.416999078749906621e+05,2.764365514401455926e+02,2.365557356914558795e+01
2.775903614457831281e+04,3.416783477873134543e+05,2.893647606124846448e+02,3.228745207399462203e+01
3.469879518072288920e+04,3.416557789530950249e+05,3.028972650389000023e+02,4.132378186601789594e+01
4.163855421686747286e+04,3.416321537100835703e+05,3.170625586928109669e+02,5.078373122359745651e+01
4.857831325301204924e+04,3.416074254783777869e+05,3.318884852814677515e+02,6.068603634067441277e+01
5.551807228915662563e+04,3.415815429327448364e+05,3.474057181625271937e+02,7.105134909256773312e+01
6.245783132530120201e+04,3.415544522300060489e+05,3.636464289926771016e+02,8.190134100122368466e+01
6.939759036144577840e+04,3.415260977365924045e+05,3.806438535358952322e+02,9.325840987164822593e+01
7.633734939759035478e+04,3.414964203711791197e+05,3.984332778382170659e+02,1.051463509826164682e+02
8.327710843373494572e+04,3.414653600014357944e+05,4.170506112539296169e+02,1.175893873102427705e+02
9.021686746987952210e+04,3.414328516432096367e+05,4.365346437314535706e+02,1.306137130588990942e+02
9.715662650602409849e+04,3.413988282470221166e+05,4.569253938161148767e+02,1.442463591617385816e+02
1.040963855421686749e+05,3.413632192634196836e+05,4.782649576946222396e+02,1.585157788857136723e+02
1.110361445783132513e+05,3.413259515784942196e+05,5.005969434566324594e+02,1.734514780491584816e+02
1.179759036144578276e+05,3.412869481684512575e+05,5.239672832915534855e+02,1.890845482571652099e+02
1.249156626506024040e+05,3.412461284264561255e+05,5.484240343128296900e+02,2.054475392309941810e+02
1.318554216867469950e+05,3.412034083521480788e+05,5.740172498169830533e+02,2.225743980349331821e+02
1.387951807228915568e+05,3.411587004275080981e+05,6.007990690568835817e+02,2.405005034349947550e+02
1.457349397590361477e+05,3.411119135291071143e+05,6.288237668098821587e+02,2.592627040830429337e+02
1.526746987951807096e+05,3.410629512288555270e+05,6.581487407315004248e+02,2.789000304129568804e+02
1.596144578313253005e+05,3.410117131286275689e+05,6.888337343389534908e+02,2.994531370334653957e+02
1.665542168674698914e+05,3.409580954690069193e+05,7.209404837466943263e+02,3.209640472463746619e+02
1.734939759036144533e+05,3.409019873411522130e+05,7.545349112599420778e+02,3.434777475878522637e+02
1.804337349397590442e+05,3.408432748557521845e+05,7.896847124497414825e+02,3.670404317980527367e+02
1.873734939759036060e+05,3.407818388539965381e+05,8.264606810057809980e+02,3.917004649976870496e+02
1.943132530120481970e+05,3.407175541858672514e+05,8.649371191956577150e+02,4.175086949371150240e+02
2.012530120481927588e+05,3.406502895223478554e+05,9.051919465370586977e+02,4.445185311150749499e+02
2.081927710843373497e+05,3.405799088448603870e+05,9.473058454237273054e+02,4.727853097158964601e+02
2.151325301204819407e+05,3.405062702847808250e+05,9.913629283077200398e+02,5.023667869114405562e+02
2.220722891566265025e+05,3.404292257098258706e+05,1.037450972444842364e+03,5.333233177293111567e+02
2.290120481927710935e+05,3.403486193780365284e+05,1.085662164190753629e+03,5.657184577727402939e+02
2.359518072289156553e+05,3.402642887818849413e+05,1.136092646412094382e+03,5.996185717030078877e+02
2.428915662650602462e+05,3.401760641797958524e+05,1.188842783214988231e+03,6.350930369891640339e+02
2.498313253012048081e+05,3.400837681198831997e+05,1.244017428928243135e+03,6.722144511885212523e+02
2.567710843373493990e+05,3.399872156806811108e+05,1.301725756307078427e+03,7.110585630118141580e+02
2.637108433734939899e+05,3.398862145463334746e+05,1.362081189367784873e+03,7.517042642987247518e+02
2.706506024096385809e+05,3.397805635820984608e+05,1.425202284103806278e+03,7.942341337977412650e+02
2.775903614457831136e+05,3.396700530317236553e+05,1.491212584092512998e+03,8.387343841838627441e+02
2.845301204819277045e+05,3.395544641904290183e+05,1.560240798846359894e+03,8.852950107246308562e+02
2.914698795180722955e+05,3.394335683321587276e+05,1.632421325637064228e+03,9.340103422041905787e+02
2.984096385542168864e+05,3.393071271093470277e+05,1.707894095306404779e+03,9.849787953465958026e+02
3.053493975903614191e+05,3.391748922934724833e+05,1.786804720712981407e+03,1.038302985814559861e+03
3.122891566265060101e+05,3.390366053009139141e+05,1.869304743744635743e+03,1.094089955341440827e+03
3.192289156626506010e+05,3.388919964388080989e+05,1.955552006956035484e+03,1.152451554235940648e+03
3.261686746987951919e+05,3.387407838406001683e+05,2.045711164873110192e+03,1.213504994526718519e+03
3.331084337349397829e+05,3.385826744650513865e+05,2.139953266550815897e+03,1.277372268397806238e+03
3.400481927710843156e+05,3.384173632355809095e+05,2.238456175152417927e+03,1.344180589266738934e+03
3.469879518072289065e+05,3.382445325354911038e+05,2.341404814370557233e+03,1.414062650138402205e+03
3.539277108433734975e+05,3.380638513938362594e+05,2.448991512647773106e+03,1.487157093516015721e+03
3.608674698795180884e+05,3.378749748990704538e+05,2.561416272728342392e+03,1.563608828201268580e+03
3.678072289156626794e+05,3.376775447504533804e+05,2.678886668240268591e+03,1.643568581306389206e+03
3.747469879518072121e+05,3.374711883440534584e+05,2.801618220652894252e+03,1.727193435293703715e+03
3.816867469879518030e+05,3.372555181867200299e+05,2.929834633842461699e+03,1.814647179437561590e+03
3.886265060240963940e+05,3.370301308546696673e+05,3.063768097174469858e+03,1.906101048155911712e+03
3.955662650602409849e+05,3.367946074136524112e+05,3.203659375443821773e+03,2.001733210903809550e+03
4.025060240963855176e+05,3.365485126725742011e+05,3.349758071821818248e+03,2.101729255604020182e+03
4.094457831325301086e+05,3.362913946400715504e+05,3.502322862590579007e+03,2.206282497337906989e+03
4.163855421686746995e+05,3.360227841016073944e+05,3.661621621068981312e+03,2.315594277323604729e+03
4.233253012048192904e+05,3.357421944751847768e+05,3.827931202729972028e+03,2.429874322085280710e+03
4.302650602409638814e+05,3.354491207976004225e+05,4.001538232076946770e+03,2.549340970322628891e+03
4.372048192771084141e+05,3.351430393318976276e+05,4.182739150692560543e+03,2.674221517409783246e+03
4.441445783132530050e+05,3.348234070645742468e+05,4.371840380538450518e+03,2.804752554887338647e+03
4.510843373493975960e+05,3.344896614773697802e+05,4.569158316865967208e+03,2.941180205764251696e+03
4.580240963855421869e+05,3.341412216426009545e+05,4.775018451506633028e+03,3.083759905892438837e+03
4.649638554216867196e+05,3.337774857807308435e+05,4.989756792763919293e+03,3.232757426505291733e+03
4.719036144578313106e+05,3.333978312771006022e+05,5.213719676047868234e+03,3.388449046851561434e+03
4.788433734939759015e+05,3.330016144165541045e+05,5.447263750668308603e+03,3.551121832777641885e+03
4.857831325301204924e+05,3.325881702446701820e+05,5.690755842017992109e+03,3.721073913311846809e+03
4.927228915662650834e+05,3.321568139953350765e+05,5.944571594605027713e+03,3.898614410059889451e+03
4.996626506024096161e+05,3.317068387162195868e+05,6.209097049427949969e+03,4.084064234352487802e+03
5.066024096385542070e+05,3.312375153890879592e+05,6.484728283836750961e+03,4.277756327075268928e+03
5.135421686746987980e+05,3.307480929075760068e+05,6.771871154376198319e+03,4.480035938047819400e+03
5.204819277108433889e+05,3.302377981778209796e+05,7.070940933265655985e+03,4.691260888913415329e+03
5.274216867469879799e+05,3.297058385154951247e+05,7.382360131708837798e+03,4.911801352796029278e+03
5.343614457831325708e+05,3.291513989055078127e+05,7.706560356595318808e+03,5.142040737896868450e+03
5.413012048192771617e+05,3.285736424029888003e+05,8.043981689542642926e+03,5.382375907468571313e+03
5.482409638554216363e+05,3.279717105811295332e+05,8.395072022014630420e+03,5.633217396855846346e+03
5.551807228915662272e+05,3.273447240289855399e+05,8.760286356716303999e+03,5.894989614298177912e+03
5.621204819277108181e+05,3.266917862779202405e+05,9.140083526113621701e+03,6.168130195966165047e+03
5.690602409638554091e+05,3.260119805959270452e+05,9.534928257798183040e+03,6.453091146274792663e+03
5.760000000000000000e+05,3.253043707731046015e+05,9.945290234605769001e+03,6.750338992289644921e+03
5.829397590361445909e+05,3.245680023500338430e+05,1.037164281375067731e+04,7.060354836215510659e+03
5.898795180722891819e+05,3.238019036907777772e+05,1.081446186780759854e+04,7.383634441414625144e+03
5.968192771084337728e+05,3.230050916342172422e+05,1.127422135298435933e+04,7.720687012798405704e+03
6.037590361445783637e+05,3.221765682729636319e+05,1.175139518722831599e+04,8.072036539808057569e+03
6.106987951807228383e+05,3.213153221672104555e+05,1.224645595778222742e+04,8.438221875007342533e+03
6.176385542168674292e+05,3.204203306685420685e+05,1.275987282696100738e+04,8.819796504496962370e+03
6.245783132530120201e+05,3.194905617878027260e+05,1.329210976862437747e+04,9.217328443572929245e+03
6.315180722891566111e+05,3.185249815253625857e+05,1.384362019639559185e+04,9.631398278241869775e+03
6.384578313253012020e+05,3.175225513622754952e+05,1.441484804394554521e+04,1.006260059377900325e+04
6.453975903614457930e+05,3.164822299758167937e+05,1.500622605098532222e+04,1.051154397319794771e+04
6.523373493975903839e+05,3.154029769468383747e+05,1.561817272281543046e+04,1.097885033034621665e+04
6.592771084337349748e+05,3.142837556580068194e+05,1.625108982621034556e+04,1.146515451578286957e+04
6.662168674698795658e+05,3.131235416089579230e+05,1.690535683098805021e+04,1.197110156005403223e+04
6.731566265060240403e+05,3.119213217553555151e+05,1.758133032758265108e+04,1.249734791706187025e+04
6.800963855421686312e+05,3.106760969471025746e+05,1.827934168345592479e+04,1.304456136944152786e+04
6.870361445783132222e+05,3.093868870813077083e+05,1.899969315281593299e+04,1.361341976587640966e+04
6.939759036144578131e+05,3.080527352278451435e+05,1.974265455597948312e+04,1.420461021617536971e+04
7.009156626506024040e+05,3.066727154035685817e+05,2.050845894644209329e+04,1.481882564998934140e+04
7.078554216867469950e+05,3.052459349959365791e+05,2.129729953406905770e+04,1.545676546999439233e+04
7.147951807228915859e+05,3.037715385313124862e+05,2.210932617675159418e+04,1.611913529193593240e+04
7.217349397590361768e+05,3.022487138519081054e+05,2.294464117233622528e+04,1.680664497575568748e+04
7.286746987951807678e+05,3.006766975177657441e+05,2.380329520037513794e+04,1.752000728185910339e+04
7.356144578313253587e+05,2.990547797054060502e+05,2.468528618732787800e+04,1.825993410726611546e+04
7.425542168674698332e+05,2.973823104133313755e+05,2.559055349278589347e+04,1.902713609388274926e+04
7.494939759036144242e+05,2.956587058401830145e+05,2.651897218014017199e+04,1.982232197967683896e+04
7.564337349397590151e+05,2.938834543906023609e+05,2.747034966036138212e+04,2.064619594903630787e+04
7.633734939759036060e+05,2.920561230857099872e+05,2.844442126505167107e+04,2.149945564923838174e+04
7.703132530120481970e+05,2.901763569106549839e+05,2.944085433581007237e+04,2.238278875353497278e+04
7.772530120481927879e+05,2.882438880276781856e+05,3.045924075618706411e+04,2.329687121613479394e+04
7.841927710843373789e+05,2.862585468263287330e+05,3.149908744624710016e+04,2.424236572742419230e+04
7.911325301204819698e+05,2.842202656365390867e+05,3.255981569860488162e+04,2.521991866485607898e+04
7.980722891566265607e+05,2.821290853670574725e+05,3.364075717765419540e+04,2.623015745528835396e+04
8.050120481927710352e+05,2.799851474158583442e+05,3.474116429304164194e+04,2.727368829110005026e+04
8.119518072289156262e+05,2.777887028452279628e+05,3.586020395843811275e+04,2.835109319633394625e+04
8.188915662650602171e+05,2.755401303577584331e+05,3.699694293383081822e+04,2.946292670841077415e+04
8.258313253012048081e+05,2.732399349973782664e+05,3.815035194634276559e+04,3.060971305627900438e+04
8.327710843373493990e+05,2.708887536177020520e+05,3.931930336409974552e+04,3.179194301819821703e+04
8.397108433734939899e+05,2.684873437874287483e+05,4.050258333353541821e+04,3.301007287903583347e+04
8.466506024096385809e+05,2.660365840413325350e+05,4.169889419246710895e+04,3.426452176620034152e+04
8.535903614457831718e+05,2.635374936278797104e+05,4.290684009463686380e+04,3.555566627748344035e+04
8.605301204819277627e+05,2.609912261062065954e+05,4.412493540710993693e+04,3.688383848668348219e+04
8.674698795180722373e+05,2.583990679888753803e+05,4.535160778239811043e+04,3.824932422872653115e+04
8.744096385542168282e+05,2.557624365208433010e+05,4.658520189378820942e+04,3.965236158536848961e+04
8.813493975903614191e+05,2.530828843488600396e+05,4.782398036252666498e+04,4.109313528861332452e+04
8.882891566265060101e+05,2.503620967633002438e+05,4.906612828663278196e+04,4.257177495006700337e+04
8.952289156626506010e+05,2.476018849487101252e+05,5.030976118308741570e+04,4.408835386820245913e+04
9.021686746987951919e+05,2.448041708251685486e+05,5.155293896511898492e+04,4.564289020971248101e+04
9.091084337349397829e+05,2.419709998156452493e+05,5.279366057680606173e+04,4.723533960754873260e+04
9.160481927710843738e+05,2.391045301185709541e+05,5.402987518664952222e+04,4.886559469477954553e+04
9.229879518072289648e+05,2.362070252686156600e+05,5.525949035162600921e+04,5.053348437975837442e+04
9.299277108433734393e+05,2.332808430543869908e+05,5.648037970824414515e+04,5.223877723736889311e+04
9.368674698795180302e+05,2.303284320518314198e+05,5.769039338321270043e+04,5.398117456495590886e+04
9.438072289156626211e+05,2.273523216181789467e+05,5.888736766637266555e+04,5.576031071544841689e+04
9.507469879518072121e+05,2.243551123116083327e+05,6.006913453729244065e+04,5.757575315109926305e+04
9.576867469879518030e+05,2.213394692674368562e+05,6.123352456383421668e+04,5.942700616872895625e+04
9.646265060240963940e+05,2.183081077433890023e+05,6.237838524682071875e+04,6.131350700979030080e+04
9.715662650602409849e+05,2.152637818050820497e+05,6.350159167295641237e+04,6.323462652196158888e+04
9.785060240963855758e+05,2.122092731207774195e+05,6.460105651179801498e+04,6.518967036742455821e+04
9.854457831325301668e+05,2.091473907663174614e+05,6.567472602719473070e+04,6.717788320648782246e+04
9.923855421686746413e+05,2.060809498692794878e+05,6.672060241348673298e+04,6.919844771723379381e+04
9.993253012048192322e+05,2.030127573411343328e+05,6.773675674003206950e+04,7.125048591883362678e+04
1.006265060240963823e+06,1.999456011756689986e+05,6.872133705264917808e+04,7.333306177168183785e+04
1.013204819277108414e+06,1.968822552791400522e+05,6.967256074374346645e+04,7.544518397711646685e+04
1.020144578313253005e+06,1.938254593253671774e+05,7.058873227023302752e+04,7.758580840439976600e+04
1.027084337349397596e+06,1.907778994072202768e+05,7.146825975322081649e+04,7.975384083955889218e+04
1.034024096385542187e+06,1.877422007839081925e+05,7.230965885992241965e+04,8.194814035616937326e+04
1.040963855421686778e+06,1.847209327384539065e+05,7.311154588184882596e+04,8.416752137969723844e+04
1.047903614457831369e+06,1.817165979732118722e+05,7.387264467124058865e+04,8.641075735554751009e+04
1.054843373493975960e+06,1.787316085320326383e+05,7.459180561779797426e+04,8.867658585016937286e+04
1.061783132530120434e+06,1.757682835623652209e+05,7.526800438278057845e+04,9.096371205485417158e+04
1.068722891566265142e+06,1.728288512429590628e+05,7.590033802701799141e+04,9.327081073002291669e+04
1.075662650602409616e+06,1.699154493719843158e+05,7.648802188432913681e+04,9.559652874368653283e+04
1.082602409638554323e+06,1.670301012021510687e+05,7.703040544066348230e+04,9.793949335718543443e+04
1.089542168674698798e+06,1.641747173790730594e+05,7.752696755577005388e+04,1.002983150651569013e+05
1.096481927710843273e+06,1.613510959086392249e+05,7.797731408335166634e+04,1.026715900080091087e+05
1.103421686746987980e+06,1.585609273439756653e+05,7.838117227131628897e+04,1.050579003847080457e+05
1.110361445783132454e+06,1.558057792874773440e+05,7.873839589846406307e+04,1.074558248140585929e+05
1.117301204819277162e+06,1.530870994468273711e+05,7.904895998694520677e+04,1.098639405662274221e+05
1.124240963855421636e+06,1.504062161228182958e+05,7.931295787404841394e+04,1.122808260031333048e+05
1.131180722891566344e+06,1.477643415255960717e+05,7.953059971258681617e+04,1.147050587618170830e+05
1.138120481927710818e+06,1.451625682974799420e+05,7.970220361165713985e+04,1.171352280908629036e+05
1.145060240963855525e+06,1.426018725293310126e+05,7.982819105262942321e+04,1.195699364180395496e+05
1.152000000000000000e+06,1.400831164562890481e+05,7.990908061346755130e+04,1.220078029302434006e+05
1.158939759036144475e+06,1.376070492038715747e+05,7.994548865188004856e+04,1.244474621442483622e+05
1.165879518072289182e+06,1.351743078006103751e+05,7.993813073152949801e+04,1.268875614678600978e+05
1.172819277108433656e+06,1.327854270940348797e+05,7.988779615941597149e+04,1.293267767465491343e+05
1.179759036144578364e+06,1.304408423774379771e+05,7.979534743955839076e+04,1.317638101830036321e+05
1.186698795180722838e+06,1.281408948687427765e+05,7.966171215941845730e+04,1.341973929718387371e+05
1.193638554216867546e+06,1.258858230195355136e+05,7.948789402666990645e+04,1.366262829537945800e+05
1.200578313253012020e+06,1.236757696560021141e+05,7.927496305387317261e+04,1.390492672901246697e+05
1.207518072289156727e+06,1.215108015213233157e+05,7.902402947792320629e+04,1.414651690007534926e+05
1.214457831325301202e+06,1.193909083546754409e+05,7.873624535807735811e+04,1.438728462872471719e+05
1.221397590361445677e+06,1.173160087764932687e+05,7.841279724164077197e+04,1.462711939818659157e+05
1.228337349397590384e+06,1.152859349326033116e+05,7.805492327815269527e+04,1.486591417892439640e+05
1.235277108433734858e+06,1.133004531616700697e+05,7.766388946380931884e+04,1.510356573745205824e+05
1.242216867469879566e+06,1.113592757823132124e+05,7.724097623513071449e+04,1.533997479825560295e+05
1.249156626506024040e+06,1.094620615857525991e+05,7.678747816554769815e+04,1.557504602486996737e+05
1.256096385542168748e+06,1.076084197902504093e+05,7.630469955600185494e+04,1.580868806537477358e+05
1.263036144578313222e+06,1.057978952390604536e+05,7.579396858508254809e+04,1.604081361758569838e+05
1.269975903614457930e+06,1.040299946620900446e+05,7.525661139188312518e+04,1.627133939460268011e+05
1.276915662650602404e+06,1.023041897399864101e+05,7.469394907087837055e+04,1.650018611891352048e+05
1.283855421686746879e+06,1.006199192650081241e+05,7.410729572922459920e+04,1.672727850057672767e+05
1.290795180722891586e+06,9.897659061546895828e+04,7.349795681440705084e+04,1.695254525701239763e+05
1.297734939759036060e+06,9.737357171227686922e+04,7.286723541385630961e+04,1.717591928738668212e+05
1.304674698795180768e+06,9.581021211507097178e+04,7.221641482628228550e+04,1.739733730586467427e+05
1.311614457831325242e+06,9.428584206143098709e+04,7.154675938733306248e+04,1.761673985512359650e+05
1.318554216867469950e+06,9.279977527881738206e+04,7.085951236852268630e+04,1.783407123526599316e+05
1.325493975903614424e+06,9.135130905076845374e+04,7.015589517354368581e+04,1.804927957756878459e+05
1.332433734939759132e+06,8.993972312756541942e+04,6.943710730928281555e+04,1.826231695631517796e+05
1.339373493975903606e+06,8.856429112120531499e+04,6.870432024372527667e+04,1.847313886350694229e+05
1.346313253012048081e+06,8.722427972198541102e+04,6.795867760486018960e+04,1.868170426731543848e+05
1.353253012048192788e+06,8.591895099836002919e+04,6.720129401219809370e+04,1.888797549894418917e+05
1.360192771084337262e+06,8.464756271311279852e+04,6.643325279237746145e+04,1.909191844945097400e+05
1.367132530120481970e+06,8.340937055508178310e+04,6.565560538290182012e+04,1.929350240620163968e+05
1.374072289156626444e+06,8.220363183624616067e+04,6.486937211501197453e+04,1.949269960487418866e+05
1.381012048192771152e+06,8.102960605204552121e+04,6.407554121695863432e+04,1.968948527309958590e+05
1.387951807228915626e+06,7.988655629119179503e+04,6.327506877370035363e+04,1.988383749351078586e+05
1.394891566265060334e+06,7.877375062493192672e+04,6.246887668357403163e+04,2.007573726914940635e+05
1.401831325301204808e+06,7.769046350779067143e+04,6.165784813012245286e+04,2.026516883620868903e+05
1.408771084337349283e+06,7.663597615889176086e+04,6.084283607753957767e+04,2.045211877635686833e+05
1.415710843373493990e+06,7.560957751316325448e+04,6.002466088085774390e+04,2.063657616059790016e+05
1.422650602409638464e+06,7.461056483258890512e+04,5.920411069811722700e+04,2.081853244692939043e+05
1.429590361445783172e+06,7.363824461646216514e+04,5.838194144650578528e+04,2.099798139370320423e+05
1.436530120481927646e+06,7.269193752166090417e+04,5.755886903890118265e+04,2.117491934394379205e+05
1.443469879518072354e+06,7.177097384973079897e+04,5.673557942045852542e+04,2.134934467298106756e+05
1.450409638554216828e+06,7.087469425489235437e+04,5.591272858690749854e+04,2.152125771582001471e+05
1.457349397590361536e+06,7.000245059821051836e+04,5.509094221812568139e+04,2.169066071836638148e+05
1.464289156626506010e+06,6.915360599301519687e+04,5.427081675119567808e+04,2.185755772557891323e+05
1.471228915662650717e+06,6.832753901132244209e+04,5.345291377617007674e+04,2.202195472125074884e+05
1.478168674698795192e+06,6.752364181430036842e+04,5.263776402221969329e+04,2.218385941634799528e+05
1.485108433734939666e+06,6.674131743147548696e+04,5.182587263153454842e+04,2.234328099369899719e+05
1.492048192771084374e+06,6.597998134169081459e+04,5.101771753226465080e+04,2.250023011260445637e+05
1.498987951807228848e+06,6.523906125631577743e+04,5.021375060329100234e+04,2.265471881403932639e+05
1.505927710843373556e+06,6.451799885725228523e+04,4.941439612060122454e+04,2.280676050221464830e+05
1.512867469879518030e+06,6.381625218312798097e+04,4.862004827385577664e+04,2.295636995430162642e+05
1.519807228915662738e+06,6.313328985768404527e+04,4.783107980744844826e+04,2.310356303348675137e+05
1.526746987951807212e+06,6.246859302735915117e+04,4.704784006611720542e+04,2.324835669065236580e+05
1.533686746987951919e+06,6.182165513961307443e+04,4.627065595378921716e+04,2.339076889065977302e+05
1.540626506024096394e+06,6.119198215020127827e+04,4.549983234088937752e+04,2.353081855089094024e+05
1.547566265060240868e+06,6.057909582927213341e+04,4.473564860897758626e+04,2.366852555617503240e+05
1.554506024096385576e+06,5.998252904633225990e+04,4.397836507443286973e+04,2.380391058792349068e+05
1.561445783132530050e+06,5.940182630096663343e+04,4.322822289635055495e+04,2.393699508026828698e+05
1.568385542168674758e+06,5.883654382594754134e+04,4.248544447963280982e+04,2.406780116944196925e+05
1.575325301204819232e+06,5.828624926930495712e+04,4.175023437467357144e+04,2.419635163560215151e+05
1.582265060240963940e+06,5.775052385339497414e+04,4.102277747208689107e+04,2.432266986745182076e+05
1.589204819277108414e+06,5.722896038701615180e+04,4.030324165537199588e+04,2.444677979576119105e+05
1.596144578313253121e+06,5.672116203874885105e+04,3.959177960399685981e+04,2.456870583572543401e+05
1.603084337349397596e+06,5.622674278296206467e+04,3.888852876129961078e+04,2.468847284557383973e+05
1.610024096385542070e+06,5.574532704958391696e+04,3.819361213698652136e+04,2.480610608134296490e+05
1.616963855421686778e+06,5.527655048348677519e+04,3.750713805812746432e+04,2.492163114583858696e+05
1.623903614457831252e+06,5.482006022364764794e+04,3.682920034296020458e+04,2.503507394333922712e+05
1.630843373493975960e+06,5.437551233663919993e+04,3.615988109105993499e+04,2.514646065723009815e+05
1.637783132530120434e+06,5.394257251065882156e+04,3.549925042738227785e+04,2.525581770619589952e+05
1.644722891566265142e+06,5.352091573154086655e+04,3.484736716782728763e+04,2.536317171006319404e+05
1.651662650602409616e+06,5.311022593414209405e+04,3.420427948561328958e+04,2.546854945802447328e+05
1.658602409638554323e+06,5.271019740097076283e+04,3.357002417099155718e+04,2.557197784280378255e+05
1.665542168674698798e+06,5.232053392457062000e+04,3.294462764465968212e+04,2.567348384307697997e+05
1.672481927710843273e+06,5.194094698612613138e+04,3.232810773121111924e+04,2.577309452826628694e+05
1.679421686746987980e+06,5.157115638077806943e+04,3.172047347099450053e+04,2.587083701482275501e+05
1.686361445783132454e+06,5.121088994269781688e+04,3.112172562573380128e+04,2.596673844315684983e+05
1.693301204819277162e+06,5.085988329273155250e+04,3.053185715916216941e+04,2.606082595481063763e+05
1.700240963855421636e+06,5.051788051342935796e+04,2.995085342122224029e+04,2.615312660653484927e+05
1.707180722891566344e+06,5.018463317705864756e+04,2.937869280816148603e+04,2.624366740147799719e+05
1.714120481927710818e+06,4.985989982445648639e+04,2.881534726915965803e+04,2.633247529063839465e+05
1.721060240963855525e+06,4.954344601848831371e+04,2.826078262235676812e+04,2.641957713591550128e+05
1.728000000000000000e+06,4.923504411137050920e+04,2.771495893850817447e+04,2.650499969501214218e+05

```
</details>

Any feedback is more than welcome!

This PR depends on #7 , so that one should be merged first.

### CODE REVIEW

**Comment by sasalatart** [comment]
Also, it seems this PR was showing https://github.com/open-sir/open-sir/pull/7's diff as well. Did you branch out from that branch? If that is the case, remember to make this PR point to that branch. As soon as you merge that other PR, then you rebase/update this with master, and make this PR point to master

**Comment by jia200x** [comment]
Thanks for the review! 

> Also, it seems this PR was showing #7 
diff as well. Did you branch out from that branch? If that is the case, remember to make this PR point to that branch. As soon as you merge that other PR, then you rebase/update this with master, and make this PR point to master

Yes, as described in the description, this depends on #7. As soon as #7 gets merged, I will rebase

**Comment by jia200x** [comment]
#7 was merged, I will rebase asap

**Comment by jia200x** [comment]
done!

**Pull request merged**
